/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    services: Service;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    settings: Setting;
    homepage: Homepage;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'super-admin' | 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO.
   */
  alt?: string | null;
  caption?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL key, e.g. central-filtration. Auto-filled from the name.
   */
  slug: string;
  /**
   * Set a parent to make this a subcategory.
   */
  parent?: (number | null) | Category;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  featured?: boolean | null;
  /**
   * Eligible for the homepage Featured section.
   */
  showOnHomepage?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  availability?: ('available' | 'on-order' | 'out-of-stock') | null;
  name: string;
  sku?: string | null;
  /**
   * URL segment, e.g. central-filter-jumbo. Auto-filled from the English name.
   */
  slug: string;
  category?: (number | null) | Category;
  /**
   * Optional — a child of the category.
   */
  subcategory?: (number | null) | Category;
  /**
   * One or two sentences for cards and hero.
   */
  shortDescription: string;
  /**
   * Rich text — the main product write-up.
   */
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Primary product image (transparent PNG ok).
   */
  mainImage: number | Media;
  /**
   * Unlimited. Drag to reorder.
   */
  gallery?: (number | Media)[] | null;
  /**
   * e.g. Pressure → 6 Bar, Stages → 7.
   */
  specs?:
    | {
        label: string;
        value: string;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Bullet list, e.g. Removes chlorine.
   */
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. Filter, Installation kit, Manual.
   */
  included?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * PDF catalog, manual, warranty, certificates.
   */
  downloads?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to auto-show 4 products from the same category.
   */
  relatedProducts?: (number | Product)[] | null;
  /**
   * Product-specific questions and answers.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  featured?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  /**
   * Optional icon name.
   */
  icon?: string | null;
  /**
   * Short label, e.g. Water Solutions.
   */
  name: string;
  /**
   * The large title on the page.
   */
  headline: string;
  /**
   * URL segment. Auto-filled from the name — keep it stable.
   */
  slug: string;
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  /**
   * Unlimited. Drag to reorder.
   */
  gallery?: (number | Media)[] | null;
  features?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        step: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Show on the homepage.
   */
  featured?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  title: string;
  /**
   * URL segment. Auto-filled from the name — keep it stable.
   */
  slug: string;
  /**
   * e.g. Residential villa.
   */
  category?: string | null;
  location?: string | null;
  completionDate?: string | null;
  /**
   * Optional.
   */
  clientName?: string | null;
  /**
   * Summary shown in listings and the hero.
   */
  shortDescription: string;
  challenge?: string | null;
  solution?: string | null;
  outcome?: string | null;
  scope?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  heroImage?: (number | null) | Media;
  /**
   * Unlimited. Drag to reorder.
   */
  gallery?: (number | Media)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  featured?: T;
  showOnHomepage?: T;
  order?: T;
  availability?: T;
  name?: T;
  sku?: T;
  slug?: T;
  category?: T;
  subcategory?: T;
  shortDescription?: T;
  fullDescription?: T;
  mainImage?: T;
  gallery?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  included?:
    | T
    | {
        item?: T;
        id?: T;
      };
  downloads?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  relatedProducts?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  featured?: T;
  order?: T;
  icon?: T;
  name?: T;
  headline?: T;
  slug?: T;
  shortDescription?: T;
  fullDescription?: T;
  heroImage?: T;
  gallery?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  process?:
    | T
    | {
        step?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  featured?: T;
  order?: T;
  title?: T;
  slug?: T;
  category?: T;
  location?: T;
  completionDate?: T;
  clientName?: T;
  shortDescription?: T;
  challenge?: T;
  solution?: T;
  outcome?: T;
  scope?:
    | T
    | {
        item?: T;
        id?: T;
      };
  heroImage?: T;
  gallery?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. +962792300005
   */
  whatsapp?: string | null;
  email?: string | null;
  address?: string | null;
  workingHours?: string | null;
  /**
   * Google Maps link.
   */
  mapUrl?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  linkedin?: string | null;
  twitter?: string | null;
  footerTagline?: string | null;
  copyright?: string | null;
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * e.g. G-XXXXXXX
   */
  googleAnalyticsId?: string | null;
  /**
   * e.g. GTM-XXXXXX
   */
  gtmId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroEyebrow?: string | null;
  heroTitleTop?: string | null;
  heroTitleAccent?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Optional background video.
   */
  heroVideo?: (number | null) | Media;
  heroPrimaryLabel?: string | null;
  heroPrimaryHref?: string | null;
  heroSecondaryLabel?: string | null;
  heroSecondaryHref?: string | null;
  about?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  why?: {
    eyebrow?: string | null;
    title?: string | null;
    pillars?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  solutions?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          eyebrow?: string | null;
          title: string;
          description?: string | null;
          bullets?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          image?: (number | null) | Media;
          href?: string | null;
          ctaLabel?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  featuredProducts?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    exploreLabel?: string | null;
    viewAllLabel?: string | null;
  };
  featuredProject?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    ctaLabel?: string | null;
  };
  process?: {
    eyebrow?: string | null;
    title?: string | null;
    steps?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          quote: string;
          name: string;
          role?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  stats?: {
    eyebrow?: string | null;
    items?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    whatsappText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  whatsapp?: T;
  email?: T;
  address?: T;
  workingHours?: T;
  mapUrl?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  linkedin?: T;
  twitter?: T;
  footerTagline?: T;
  copyright?: T;
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  googleAnalyticsId?: T;
  gtmId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitleTop?: T;
  heroTitleAccent?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroVideo?: T;
  heroPrimaryLabel?: T;
  heroPrimaryHref?: T;
  heroSecondaryLabel?: T;
  heroSecondaryHref?: T;
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  why?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        pillars?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  solutions?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              href?: T;
              ctaLabel?: T;
              id?: T;
            };
      };
  featuredProducts?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        exploreLabel?: T;
        viewAllLabel?: T;
      };
  featuredProject?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
      };
  process?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              quote?: T;
              name?: T;
              role?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        eyebrow?: T;
        items?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        whatsappText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}